name: Test

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Nix flake check ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - uses: wimpysworld/nothing-but-nix@main
        if: matrix.os == 'ubuntu-latest'

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          ref: ${{ github.head_ref || github.ref }}
          token: ${{ secrets.PAT }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - run: nix flake metadata

      - run: |
          cat <<-EOF > modules/ci-runtime.nix
          {
            _module.args.CI = true;
          }
          EOF

      - run: nix flake check
